---
title: "R Notebook"
output: html_notebook
---



```{r}
require("rgdal")
require("maptools")
require("ggplot2")
require("plyr")

library("rgdal")
library(maptools)
library(ggplot2); theme_set(theme_minimal())
library(plyr)
library(dplyr)
  
utah = readOGR("/Users/jasonwhittle/Documents/school_district_mapping/cb_2016_49_unsd_500k", "cb_2016_49_unsd_500k")

```

```{r}
slco <- subset(utah, NAME == "Granite School District" | 
                 NAME == "Murray School District" |
                 NAME == "Salt Lake City School District" | 
                 NAME == "Jordan School District" | 
                 NAME == "Canyons School District")


gsd <- subset(utah, NAME == "Granite School District")

slco %>% ggplot() + 
  geom_polygon(aes(x=long, y= lat, group= group), fill = "#00abe1", color = "black") + 
  coord_fixed(1.3) + 
  geom_point(x = -111.9444, y = 40.6723) +
  geom_point(x = -111.9743, y = 40.5846) + 
  geom_point(x = -111.8869, y = 40.7352) + 
  geom_point(x = -111.9010, y = 40.5752) +  
  geom_point(x = -111.9482, y = 40.4931, shape = 5) +  
  labs(x="", y="", title="Salt Lake County School Districts") 


```


```{r}
# library(raster)
# 
# s <- shapefile("/Users/jasonwhittle/Documents/school_district_mapping/cb_2016_49_unsd_500k/cb_2016_49_unsd_500k.shp")
# 
# r <- subset(s, NAME == "Granite School District" | NAME == "Murray School District" |
#               NAME == "Salt Lake City School District" | NAME == "Jordan School District" | 
#               NAME == "Canyons School District")
# t <- plot(r)
# t + labs(title= "Granite School District")
```

